SAWCRUHTEEZ(SAR_reverse, SAR_reverse_up, SAR_reverse_down, SAR_up, SAR_down,
             TSR_reverse, TSR_setup_up, TSR_setup_down, TSR_reverse_up, TSR_reverse_down) =>

    var trend_has_had_tsr_trigger = false
    var recent_tsr_trigger_pre_trend = false

    profit_take_buy = false
    profit_take_sell = false
    stop_and_reverse_buy = false
    stop_and_reverse_sell = false
    stop_buy = false
    stop_sell = false
    long = false
    short = false
    buy_signal = false
    sell_signal = false


    signal = string(na)

    RSI = rsi(close, 14)

    if (SAR_reverse_up and TSR_reverse_up)
        signal := "SAR"

        trend_has_had_tsr_trigger := true
        stop_and_reverse_buy := true
    else
        if (SAR_reverse_down and TSR_reverse_down)
            signal := "SAR"

            trend_has_had_tsr_trigger := true
            stop_and_reverse_sell := true
        else
            if (SAR_reverse_up and not TSR_reverse_up)
                if (recent_tsr_trigger_pre_trend)
                    signal := "SAR"

                    trend_has_had_tsr_trigger := true
                    stop_and_reverse_buy := true
                else
                    signal := "Stop"

                    trend_has_had_tsr_trigger := false
                    stop_buy := true
            else
                if (SAR_reverse_down and not TSR_reverse_down)
                    if (recent_tsr_trigger_pre_trend)
                        signal := "SAR"

                        trend_has_had_tsr_trigger := true
                        stop_and_reverse_sell := true
                    else
                        signal := "Stop"

                        trend_has_had_tsr_trigger := false
                        stop_sell := true


                else

                    if (not trend_has_had_tsr_trigger)
                        if (TSR_reverse_up and SAR_up)
                            signal := "Long"

                            long := true
                            trend_has_had_tsr_trigger := true
                        else
                            if (TSR_reverse_down and SAR_down)
                                signal := "Short"

                                short := true
                                trend_has_had_tsr_trigger := true


                    if (not long and not short)
                        if (TSR_setup_down and SAR_up)
//                         and (RSI <= 75))
                            signal := "Buy"

                            buy_signal := true
                        else
                            if (TSR_reverse_down and SAR_up)
//                             and (RSI <= 75))
                                signal := "Buy"

                                buy_signal := true
                            else
                                if (TSR_reverse_down and SAR_up)
//                                 and (RSI > 75))
                                    signal := "Sell-FPT"

                                    profit_take_sell := true



                                else
                                    if (TSR_setup_up and SAR_down)
//                                     and (RSI >= 25))
                                        signal := "Sell"

                                        sell_signal := true
                                    else
                                        if (TSR_reverse_up and SAR_down)
//                                         and (RSI >= 25))
                                            signal := "Sell"

                                            sell_signal := true
                                        else
                                            if (TSR_reverse_up and SAR_down)
//                                             and (RSI < 25))
                                                signal := "Buy-FPT"

                                                profit_take_buy := true
    if (SAR_reverse_up or SAR_reverse_down)
        recent_tsr_trigger_pre_trend := false

    if (TSR_reverse_up and SAR_down)
        recent_tsr_trigger_pre_trend := true
    if (TSR_reverse_down and SAR_down)
        recent_tsr_trigger_pre_trend := false
    if (TSR_reverse_down and SAR_up)
        recent_tsr_trigger_pre_trend := true
    if (TSR_reverse_up and SAR_up)
        recent_tsr_trigger_pre_trend := false






    [signal, profit_take_buy, profit_take_sell, stop_and_reverse_buy, stop_and_reverse_sell, stop_buy, stop_sell, long, short, buy_signal, sell_signal]

